### ISSUE TITLE
Drop Shadow Toggle / Settings

### ISSUE THREAD

**Issue by HazardousMonkey** [CTN-Originals/LethalCompany-CrossHair#1]
I like this mod, but a toggle or additional settings for the drop shadow on the UI element would be greatly appreciated

example of why:
![image](https://github.com/CTN-Originals/LethalCompany-CrossHair/assets/49216094/d0a24896-c706-4278-b81c-d8859788eba3)

**Comment by 8CTN8** [comment]
Ah yeah that couldn't hurt of course... I'll add that soon, thanks for the suggestion!

**Comment by 8CTN8** [comment]
[Release 1.0.3](https://github.com/CTN-Originals/LethalCompany-CrossHair/releases/tag/1.0.3)
