### ISSUE TITLE
Incompability with the mod "Spectators" & UI-related errors with the mod on.

### ISSUE THREAD

**Issue by koocgum** [CTN-Originals/LethalCompany-CrossHair#2]
the mod [Spectators](https://thunderstore.io/c/lethal-company/p/JoshFoRs/Spectators/) seems to be incompatible with the crosshairs mod, as when having both enabled and joining a non-modded lobby, the crosshair does not appear, and instead, outputs UI-related errors in the console

**Comment by 8CTN8** [comment]
@koocgum informed me that the other mod has fixed the issue and that it doesn't effect this mod anymore. If this ever pops up again, feel free to open it again.
