### ISSUE TITLE
Incompatible with GeneralImprovements

### ISSUE THREAD

**Issue by smilepeak** [CTN-Originals/LethalCompany-CrossHair#4]
The new version 1.1.0 seems to be incompatible with GeneralImprovements MOD. I don't know whose problem it is, but I have already provided feedback to another author
https://thunderstore.io/c/lethal-company/p/ShaosilGaming/GeneralImprovements/

**Comment by smilepeak** [comment]
It seems that the author of GeneralImprovements has fixed it

**Comment by CTNOriginals** [comment]
Thanks for reporting and updating @smilepeak
